name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CI: false

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in package-lock.json and package.json
        id: check
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
          git diff --name-only origin/main package-lock.json package.json
          echo "::set-output name=changed::$(git diff --name-only origin/main package-lock.json package.json)"

      - name: Install dependencies
        if: steps.check.outputs.changed == 'package-lock.json'
        run: echo "package-lock.json has changed"

      - name: Install dependencies
        if: steps.check.outputs.changed == 'package.json'
        run: echo "package.json has changed"

